### PR TITLE
Refactored UnitedStates::Documents::Bills into more manageable bits

### PR DESCRIPTION
**Pull request by parkr**
This is just a refactoring of the Bills processing so each method only handles one concern (where it makes sense to do that).

### CODE REVIEW

**Comment by parkr** [comment]
I'd also love to hear your reasoning for using divs and spans instead of more semantic HTML tag names, like `p`, `article`, `h1`, `ul` and such. There are tag names in the XML that would make it relatively easy to build HTML that uses tags which are a bit more specific to its content. :)

**Comment by konklone** [comment]
Thanks for this! I'm happy to merge it. I may remove those "Static:" markers though, since every method is going to be static in this system for the foreseeable future. It's really more of a module than a class.

I should really add some unit tests so I can be more confident that it hasn't changed the behavior, but that's on me to start, and offhand this looks great.

The reasoning for using divs/spans is simply time and maintenance - I don't want the script to have to know the entire potential schema of these bill and amendment documents. It should only have to know about the parts of the document it has to make intelligent decisions about, like citations. Even now, it doesn't detect all things which might be better off as divs than spans, and I'm fine with that.

The other main benefit is that I'd like to present the most display-neutral piece of HTML possible. I don't want people to have to use a CSS reset template, or manually override attributes, in order to start from scratch when styling the bill. Using `h1` and `ul` tags would necessitate that.

I'd welcome a patch which added a 'semantic' option that causes the transformer to attempt to map XML tags to a semantic HTML equivalent. Your refactoring would make that easier, since you could just use a different `xml_to_html` method. There's [quite a DTD](http://www.gpo.gov/fdsys/pkg/BILLS-113hr624rfs/xml/bill.dtd) to process, though. :)

**Comment by konklone** [comment]
BTW, are you using this anywhere?

**Comment by parkr** [comment]
Wow, thanks! I appreciate the explanation of the HTML output as well – I was confused when I opened the HTML in my browser (no styles) and saw a lot of output just jammed all in there :) The HTML is almost like syntax highlighting for languages – class-based manipulation of the content.

Why not have the `Bills` module create instances of `Bill`? I could create instances of `Bill` and call things like `to_html`, `to_json` and such and persist the XML so it doesn't have to be re-parsed every time. The `Bill` class could then be the data model which matches the DTD. But that's a level of flexibility you might not need.

Not using this anywhere - I was just looking around this organisation. I want to eventually work for/with (federal) government entities to increase transparency. I'm also thinking about writing some API/worker system which pulls data, stores it (like this bills data) and makes it accessible as JSON to anyone who registers an application. The data is there, it's just not yet available via a nice API (that I have seen). :)

**Comment by parkr** [comment]
Additionally, why do you organise your code as you do? I'm used to seeing a gem lain out like this:

``` text
.
|- us-documents.gemspec
|- lib/
 |- us-documents.rb
 |- us-documents/
  |- bill.rb
  |- bills.rb
|- spec/
 |- spec_helper.rb
 |- bill_spec.rb
 |- bills_spec.rb
# ... etc
```

**Comment by konklone** [comment]
It's used as a module and not as a real class because it's designed to be used as a Unix-style "dumb" pipe - text goes in, text comes out, and each class boils down to one method that takes in that text. This maps it very cleanly to the command line interface I included with the gem so that people in non-Ruby environments could make use of it. 

The directory structure is laid out like this because this repository was founded as a place for some people in the community to try out different things with different kinds of documents. So I did something with bills and the Federal Register, and it was useful enough to put into a gem, but the repository may be used for more than just the gem.

**Pull request merged**
